version: "3.8"
services:
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    depends_on:
      gluetun:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/jackett:/config
      - ${DATA_FOLDER}/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_FOLDER}/sonarr:/config
      - ${DATA_FOLDER}/media/TV Shows:/tv #optional
      - ${DATA_FOLDER}/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - networkarr

  sonarr-cz:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-cz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/sonarr-cz:/config
      - ${DATA_FOLDER}/media/TV Shows CZ:/tv #optional
      - ${DATA_FOLDER}/downloads:/downloads #optional
    ports:
      - 8990:8989
    restart: unless-stopped
    networks:
      - networkarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/radarr:/config
      - ${DATA_FOLDER}/media/Movies:/movies #optional
      - ${DATA_FOLDER}/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - networkarr

  radarr-cz:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-cz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/radarr-cz:/config
      - ${DATA_FOLDER}/media/Movies CZ:/movies #optional
      - ${DATA_FOLDER}/downloads:/downloads #optional
    ports:
      - 7879:7878
    restart: unless-stopped
    networks:
      - networkarr

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - networkarr

  overseerr-cz:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr-cz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/overseerr-cz:/config
    ports:
      - 5056:5055
    restart: unless-stopped
    networks:
      - networkarr

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - ${CONFIG_FOLDER}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      - networkarr

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Europe/Copenhagen
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    volumes:
      - ${CONFIG_FOLDER}/plex:/config
      - ${DATA_FOLDER}/transcode:/transcode
      - ${DATA_FOLDER}:/data
    devices:
      - /dev/dri:/dev/dri

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${VPN_PORT}
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    depends_on:
      gluetun:
        condition: service_started
    volumes:
      - ${CONFIG_FOLDER}/qbittorrent:/config
      - ${DATA_FOLDER}/downloads:/downloads
    network_mode: service:gluetun

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    ports:
      - 8080:8080
      - ${VPN_PORT}:${VPN_PORT}
      - ${VPN_PORT}:${VPN_PORT}/udp
      - 9117:9117
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - FIREWALL_VPN_INPUT_PORTS=${VPN_PORT}
      - SERVER_COUNTRIES=${VPN_COUNTRY}

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${DATA_FOLDER}/nginx:/usr/share/nginx/html:ro

  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      - networkarr
